### ISSUE TITLE
unable to load Disqus

### ISSUE THREAD

**Issue by muescha** [andygrunwald/andygrunwald.github.io#9]
There is this error message:

``` 
unable to load Disqus. If you are a moderator 
please see our troubleshooting guide.
```

**Comment by andygrunwald** [comment]
Thanks for reaching out.
I saw it yesterday and didn't had time to fix it. To push out a new article was more important.
Will let you know once this is fixed. Thx.

**Comment by andygrunwald** [comment]
I deactivated Disqus for now. Will fix it properly at a later stage

**Comment by andygrunwald** [comment]
Also fixed. Disqus is active again.
